name: Cron Test

on:
  schedule:
    # 2시간마다 실행 (정각 회피: 17분)
    # - cron: '17 */2 * * *'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Show time
        run: date
